package bsu.fpmi.educational_practice2017;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.awt.Panel;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author nera_gatta
 */
public class NewJPanel extends Panel{
    
    private char commandKey = 's';

    /**
     * Creates new form MyPanel
     */
    public NewJPanel() {
        initComponents();
        jButton1.setFocusable(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        jLabel1.setText("Label");

        jRadioButton1.setText("RadioButton1");
        jRadioButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton1KeyPressed(evt);
            }
        });

        jRadioButton2.setText("RadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jRadioButton2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButton2KeyPressed(evt);
            }
        });

        jButton1.setText("Button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jButton1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabel1)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(jButton1, "Button is pressed \n left selected: "+jRadioButton1.isSelected()+"\n rigth selected: "+jRadioButton2.isSelected());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyTyped
        // TODO add your handling code here:
        if (evt.getKeyChar() == commandKey) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jButton1KeyTyped

    private void jRadioButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton1KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == commandKey) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jRadioButton1KeyPressed

    private void jRadioButton2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButton2KeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() == commandKey) {
            jButton1.doClick();
        }
    }//GEN-LAST:event_jRadioButton2KeyPressed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables
    
public enum RadioButtonValues {
    radioButton, radioButton1, radioButton2;
}

public enum ButtonValues {
    button, button1, button2
}

public enum LabelValues {
    label, label1, label2
}

public LabelValues labels;

 public void setLabel(LabelValues labels) {
        this.labels = labels;
        switch(labels){
            //"Нажми", "Нажми кнопку", "press button"
        case label: jLabel1.setText("Press");
        break;
        case label1: jLabel1.setText("Press button");
        break;
        case label2: jLabel1.setText( "Press button, please");
        break;
        
    }
}
 
  public LabelValues getLabel() {
        return labels;
}
  
  public ButtonValues buttons;
  
  public void setButton(ButtonValues buttons) {
        this.buttons = buttons;
        switch(buttons){
            //"Нажми", "Нажми кнопку", "press button"
        case button: jButton1.setText("Press");
        break;
        case button1: jButton1.setText("Press me");
        break;
        case button2: jButton1.setText( "Press me, please");
        break;}
    }
  
  public ButtonValues getButton() {
        return buttons;
    }
  
  public RadioButtonValues radioButtons;
  
   public void setRadioButton1(RadioButtonValues radioButton) {
        this.radioButtons = radioButton;
        switch(radioButtons){
        case radioButton: jRadioButton1.setText("Choose this");
        break;
        case radioButton1: jRadioButton1.setText("Choose rigth");
        break;
        case radioButton2: jRadioButton1.setText( "Choose enother");
        break;}
    }

    public void setRadioButton2(RadioButtonValues radioButton) {
        this.radioButtons = radioButton;
        switch(radioButtons){
        case radioButton: jRadioButton2.setText("Choose this");
        break;
        case radioButton1: jRadioButton2.setText("Choose left");
        break;
        case radioButton2: jRadioButton2.setText( "Choose enother");
        break;}
    }
    
     public RadioButtonValues getRButton() {
        return radioButtons;
    }

    public char getCommandKey() {
        return commandKey;
    }

    public void setCommandKey(char commandKey) {
        this.commandKey = commandKey;
    }

    public JButton getjButton1() {
        return jButton1;
    }
    
    
    
}
