/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeMethods */

#ifndef _Included_NativeMethods
#define _Included_NativeMethods
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeMethods
 * Method:    openKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_openKey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NativeMethods
 * Method:    createKey
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_createKey
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NativeMethods
 * Method:    closeKey
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeMethods_closeKey
  (JNIEnv *, jclass);

/*
 * Class:     NativeMethods
 * Method:    deleteValue
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_deleteValue
  (JNIEnv *, jclass, jstring);

/*
 * Class:     NativeMethods
 * Method:    setValue
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeMethods_setValue
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
